### PR TITLE
docs(wiki): add images

### PR DESCRIPTION
**Pull request by vanessajones**

### CODE REVIEW

**Comment by vicrep** [comment]
Are those used anywhere? Can't see them being referenced

**Comment by vanessajones** [comment]
Don't I need to merge this first @vicrep ?

**Comment by vicrep** [comment]
@vanessajones no, we can preview the markdown in the PR editor and file references will work :) 

Also, consider using more URL friendly filenames, such as `content-adding_to_an_existing_branch.png`

**Comment by vanessajones** [comment]
Updated the names

**Comment by vicrep** [comment]
Can we add the markdown changes too?

**Comment by vanessajones** [comment]
I'm confused, the Wiki markdown seems to be separate from the repo? It's letting me update it in real-time..

**Pull request merged**
